add_rules("mode.debug", "mode.release")
add_requires("libsdl", "fmt", "libsdl_image")
option("event")
    add_cxxflags("-DDEBUG_EVENT")

target("dev")
    set_kind("binary")
    set_languages("c++20")
    set_rundir("$(projectdir)")
    set_pcxxheader("src/libheader.hpp")
    add_includedirs("src")
    add_files("src/*.cpp")
    add_packages("libsdl", "fmt", "libsdl_image")
    add_options("event")